# Generated by Django 4.2.7 on 2023-12-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog',
        ),
    ]
